---
title: "Publication year summaries"
author: "Leo Lahti"
date: "`r Sys.Date()`"
output: markdown_document
---


### Publication year

[Publication year conversions](output.tables/publication_year_conversion.csv)

[Publication year discarded](output.tables/publication_year_discarded.csv)

Publication year is available for `r sum(!is.na(df$publication_year))` documents (`r round(100*mean(!is.na(df$publication_year)))`%). The publication years span `r paste(range(na.omit(df$publication_year)), collapse = "-")`.

```{r summarypublicationyear, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=6}
# Title count per decade
df2 <- df %>% group_by(publication_decade) %>% filter(publication_decade < 2010) 
p <- ggplot(df2, aes(publication_decade)) +
     geom_bar() + scale_y_log10() +
     ggtitle("Title count timeline")
print(p)
```

### Publication frequency

Publication frequency is available for `r sum(!is.na(df$publication_frequency))` documents (`r round(100*mean(!is.na(df$publication_frequency)))`%). The links are invalid if the lists are empty.

[Publication frequency accepted](output.tables/publication_frequency_discarded.csv)

[Publication frequency conversions](output.tables/publication_frequency_conversion.csv)

[Publication frequency discarded](output.tables/publication_frequency_discarded.csv)


### Publication interval

Publication interval is available for `r sum(!is.na(df$publication_interval))` documents (`r round(100*mean(!is.na(df$publication_interval)))`%). 

[Publication interval accepted](output.tables/publication_interval_discarded.csv)

[Publication interval conversions](output.tables/publication_interval_conversion.csv)

[Publication interval discarded](output.tables/publication_interval_discarded.csv)


### Editions

Automated detection of potential first editions (first_edition field)
identifies unique author-title pairs, and proposes the first
occcurrence (earliest publication_year) as the first edition. If there
are multiple instances from the same earliest year, they are all
marked as potential first editions. Later need to check if this
information is readily available in MARC.

In this data we have `r nrow(unique(df[, c("title", "author")]))`
unique documents with an identical title and author. Out of these,
`r length(which(write_xtable(df[, c("title", "author")])$Count > 1))`
have multiple occurrences, sometimes with different publication years.
Where multiple publication years are seen, the earliest occurrence is
suggested as the first edition.







