---
title: "Subject topic preprocessing summaries"
author: "Leo Lahti"
date: "`r Sys.Date()`"
output: markdown_document
---

## Subject topics

```{r summarytopics, echo=FALSE, message=FALSE, warning=FALSE}
# List all topics
spl <- strsplit(na.omit(as.character(df$subject_topic)), ";")

# Title count per subject topic
tab <- sort(table(unlist(spl)))
tab <- tab[!names(tab) == "NA"]
tab <- rev(sort(tab)) 
```

  * `r length(unique(df$subject_topic))` [unique accepted subject topics](output.tables/subject_topic_accepted.csv)
  * [List of discarded subject topics](output.tables/subject_topic_discarded.csv)
  * `r sum(!is.na(df$subject_topic))` documents (`r round(100*mean(!is.na(df$subject_topic)))`%) are assigned a subject topic 

Top-`r ntop` subject topics and number of documents for each.

```{r summarytopics22, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=8}
p <- top_plot(df, "subject_topic", ntop)
p <- p + ggtitle(paste("Top subject topics"))
p <- p + ylab("Documents")
print(p)
```
