context("Language")
library(dplyr, quiet = TRUE)
test_that("Language recognition works correctly", {
  expect_equal(as.character(mark_languages("swe;eng")$languages), "Swedish;English")
  expect_equal(as.character(mark_languages("swe;eng")$language_primary), "Swedish")  
  expect_equal(as.character(mark_languages("swe")$languages), "Swedish")
  expect_equal(as.character(mark_languages("swe;")$languages), "Swedish")
  expect_equal(as.character(mark_languages("Swedish")$languages), "Swedish")      
  expect_equal(as.character(mark_languages("swe;eng")$languages), "Swedish;English")
  expect_equal(as.character(mark_languages("swe;eng")$languages), "Swedish;English")
  expect_equal(as.character(unlist(mark_languages(c("swe;eng", "fin", "und", "lat;eng"))[3,"languages"])), "Undetermined")
  expect_equal(as.character(unlist(mark_languages(c("swe;eng", "fin", "und", "lat;eng"))[2,"languages"])), "Finnish")
  expect_equal(as.character(unlist(mark_languages(c("swe;eng", "fin", "und", "lat;eng"))[2,"languages"])), "Finnish")
  expect_equal(as.character(unlist(mark_languages(c("swe;eng", "fin", "und", "lat;eng"))[4,"language_primary"])), "Latin")
  expect_true(mark_languages("swe;eng")[["multilingual"]])
  expect_true(!mark_languages(c("swe;eng", "lat"))[["multilingual"]][[2]])
  expect_true(mark_languages(c("swe;eng", "lat", "eng;swe"))$multilingual[[3]])
  expect_equal(mark_languages(c("swe;eng", "lat", "eng;fin"))$language_count[[3]], 2)
})
