context("Dimension table")

test_that("dimension fill works correctly", {
  dimension.table <- dimension_table()
  expect_equal(fill_dimensions(c(original="12mo", gatherings="12mo", width=13, height=NA), dimension.table)[["height"]], "18")
})



test_that("dimension polish works correctly", {

  # Fix later:		     
  #expect_equal(as.character(polish_dimensions("46 cm(2⁰)")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("29-40 cm. (4⁰; 2⁰)")$gatherings), "NA")
  #expect_equal(as.character(polish_dimensions("4⁰. '")$gatherings), "4to")
  #expect_equal(as.character(polish_dimensions("2⁰ (2 half-sheets)")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("1/2⁰; 2⁰.")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("2⁰; 1/2⁰.")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("1/2⁰? (34.5 x 16 cm.)")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("1/2⁰; 35.5 x 22.5 cm.")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("18 cm. (8vo; horizontal chain lines)")$gatherings), "8vo")
  #expect_equal(as.character(polish_dimensions("1/2⁰(?)")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("40; 34; 42 cm (2⁰; 1/2⁰; 2⁰)")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("obl4⁰.")$gatherings), "4to")
  #expect_equal(as.character(polish_dimensions("51-34 cm (2⁰-obl. 2⁰)")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("49 cm (1/2⁰, 2⁰)")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("42 cm.(2⁰)")$gatherings), "2fo")
  #expect_equal(as.character(polish_dimensions("20 cm. (4to?)")$gatherings), "4to")

  expect_equal(as.character(polish_dimensions("NA", fill = FALSE, dimtab = NULL)$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("2fo.;2fo.")$gatherings), "2fo")
  expect_equal(as.character(polish_dimensions("2fo(3?).")$gatherings), "2fo")    
  expect_equal(as.character(polish_dimensions("2fo")$gatherings), "2fo")
  expect_equal(as.character(polish_dimensions("4to;2fo")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("2fo;1to")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("4to-2fo")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("cm.4to")$gatherings), "4to")
  expect_equal(as.character(polish_dimensions("12mo.f")$gatherings), "12mo")
  expect_equal(as.character(polish_dimensions("4to.;4to")$gatherings), "4to")
  expect_equal(as.character(polish_dimensions("4to-4to")$gatherings), "4to")
  
  expect_equal(as.character(polish_dimensions("4⁰, 2⁰ and 1⁰.")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("31-44 cm (4⁰; 2⁰)")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("4⁰ and 8⁰.")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("4⁰; 2⁰.")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("4⁰; sm 2⁰; 2⁰ (30-51 cm.).")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("2⁰; 1⁰.")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("4⁰ and 2⁰.")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("2⁰; 4⁰.")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("2⁰; later, 1⁰.")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("44-55 cm (2⁰;1⁰)")$gatherings), "NA")

  expect_equal(as.character(polish_dimensions("4⁰; 43 cm (2⁰)")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("1/2.")$gatherings), "2fo")
  expect_equal(as.character(polish_dimensions("1/2")$gatherings), "2fo")
  expect_equal(as.character(polish_dimensions("8")$gatherings), "8vo")
  expect_equal(as.character(polish_dimensions("8⁰ in 4's.")$gatherings), "8vo")
  expect_equal(as.character(polish_dimensions("16⁰ in 8's.")$gatherings), "16mo")
  expect_equal(as.character(polish_dimensions("4⁰ in 8's.")$gatherings), "4to")
  expect_equal(as.character(polish_dimensions("12⁰ & 8⁰")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("21 cm. (4to and 8vo)")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("(4to and 8vo)")$gatherings), "NA")
  expect_equal(as.character(polish_dimensions("(fol)")$gatherings), "2fo")
  expect_equal(as.character(polish_dimensions("2⁰; 32 x 20 cm.")$gatherings), "2fo")
  expect_equal(as.character(polish_dimensions("Broadside. 35 x 24 cm.")$gatherings), "bs")
  expect_equal(as.character(polish_dimensions("32 cm. (fol))")$gatherings), "2fo")
  expect_equal(as.character(polish_dimensions("20 cm. (4to & 8vo)")$gatherings), "NA")

})

